### ISSUE TITLE
Feature request :)

### ISSUE THREAD

**Issue by KKingPSB** [LizLeki/brownie#1]
A nice (and hopefully easy to implement) feature might be to include the column number when using launch_varview to look at a variable. 

For example, I'm trying to find the variable that appears in the column before a set of variables because I'm hoping that will hold the brand labels for perceptual maps - but when I search for the variable the view restricts to only the matches, but if I knew what variable "number" it is (i.e. what column it's held in) I would be able to navigate to it in the "unfiltered" view.

(side note: Isn't there a way to tag this as a feature request as opposed to an issue?)

**Comment by LizLeki** [comment]
@KKingPSB , this feature is available now. You should have it after a fresh install.

**Comment by KKingPSB** [comment]
@LizLeki you're a rockstar!
